### ISSUE TITLE
Update NPM Package

### ISSUE THREAD

**Issue by fvsadem** [julieng-dup/geocoder-fr#5]
Hi,

I saw you merge the pull request in master branch.

Could you please update the npm package ?

Thanks

**Comment by julieng-dup** [comment]
Hi !

I just publish v1.0.3 on npmjs :)
The service look available, maybe a short break from this API !?

Best,
Julien.

Le 10 septembre 2020 à 14:16:50, fvsadem (notifications@github.com) a écrit:

Hi,

I saw you merge the pull request in master branch.

Could you please update the npm package ?

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/julieng-dup/geocoder-fr/issues/5>, or unsubscribe
